import Config

# Configure the database
config :pipeforge, PipeForge.Repo,
  username: System.get_env("POSTGRES_USER") || "postgres",
  password: System.get_env("POSTGRES_PASSWORD") || "postgres",
  hostname: System.get_env("POSTGRES_HOST") || "localhost",
  database: System.get_env("POSTGRES_DB") || "pipeforge_dev",
  port: String.to_integer(System.get_env("POSTGRES_PORT") || "5432"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Configure ExAws for MinIO/S3
config :ex_aws,
  access_key_id: System.get_env("MINIO_ACCESS_KEY") || "minioadmin",
  secret_access_key: System.get_env("MINIO_SECRET_KEY") || "minioadmin",
  region: System.get_env("MINIO_REGION") || "us-east-1"

config :ex_aws, :s3,
  scheme: "http://",
  host: System.get_env("MINIO_ENDPOINT") || "localhost",
  port: 9000

config :pipeforge, :storage,
  bucket: System.get_env("MINIO_BUCKET") || "pipeforge-uploads",
  region: System.get_env("MINIO_REGION") || "us-east-1",
  local_dir: System.get_env("STORAGE_LOCAL_DIR") || "priv/storage"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :pipeforge, PipeForgeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "TU98ad2hVaIODbSpfdEU/RqAQswRcsePnx7UmcV5a+ris7LUQJ77bjTFHSfLTHoE",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:pipeforge, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:pipeforge, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :pipeforge, PipeForgeWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/pipeforge_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :pipeforge, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Configure Oban for development
config :pipeforge, Oban,
  engine: Oban.Engines.Basic,
  repo: PipeForge.Repo,
  queues: [rollups: 5, alerts: 2, default: 5],
  plugins: [
    {Oban.Plugins.Cron,
     crontab: [
       # Run daily rollups at 2 AM UTC
       {"0 2 * * *", PipeForge.Rollups.DailyRollupWorker, args: %{}},
       # Run sales alerts at 2:30 AM UTC
       {"30 2 * * *", PipeForge.Alerts.SalesAlertWorker, args: %{}}
     ]},
    Oban.Plugins.Pruner
  ]

# Configure Swoosh for email alerts (development)
config :pipeforge, PipeForge.Alerts.EmailNotifier,
  adapter: Swoosh.Adapters.SMTP,
  relay: System.get_env("SMTP_HOST") || "localhost",
  port: String.to_integer(System.get_env("SMTP_PORT") || "587"),
  username: System.get_env("SMTP_USERNAME"),
  password: System.get_env("SMTP_PASSWORD"),
  ssl: false,
  tls: :if_available,
  auth: :if_available,
  retries: 1

# Alert configuration (development)
config :pipeforge,
  slack_webhook_url: System.get_env("SLACK_WEBHOOK_URL"),
  alert_email_recipients: System.get_env("ALERT_EMAIL_RECIPIENTS"),
  alert_from_email: System.get_env("ALERT_FROM_EMAIL") || "alerts@pipeforge.local"
